<div class="field mobile required">
    <label class="label" for="mobile">
      <span><?= $block->escapeHtml(__('Mobile Account')) ?></span>
    </label>
    <div class="control">
       <input type="text" 
       name="mobile" id="mobile" value="" 
       title="<?= $block->escapeHtmlAttr(__('Mobile Account')) ?>" 
       class="input-text" 
       data-validate="{required:true}">
    </div>
</div>