<?php	
/**	
* Copyright Â© 2013-2017 Magento, Inc. All rights reserved.	
* See COPYING.txt for license details.	
*/	
// @codingStandardsIgnoreFile	
/** @var $block \Magento\Catalog\Block\Product\View */	
?>	
 	
<?php $_product = $block->getProduct(); ?>	
<?php $buttonTitle = __('Add to Cart'); ?>	
<?php if ($_product->isSaleable()): ?>	
<div class="box-tocart">	
   <div class="fieldset">	
       <?php if ($block->shouldRenderQuantity()): ?>	
       <div class="field qty">	
	   <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
 	
<script type="text/x-magento-init">	
{	
   "*": {	
	   "Magento_Ui/js/core/app": {
	       "components": {
	           "change_qty": {
	               "component": "Meetanshi_AddQuantity/js/view/product/view/change_qty",
	               "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
	           }
	       }
	   }
   }	
}	
</script>	
 	
<div class="control" data-bind="scope: 'change_qty'">	
   <button data-bind="click: decreaseQty">-</button>	
   <input  data-bind="value: qty()"	
   type="number"	
   name="qty"	
   id="qty"	
   maxlength="10"	
   title="<?php echo __('Qty') ?>"	
   class="input-text qty"	
   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"	
   />	
 	
   <button data-bind="click: increaseQty">+</button>	
</div>	
       </div>	
       <?php endif; ?>	
       <div class="actions">	
	   <button type="submit"
	           title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
	           class="action primary tocart"
	           id="product-addtocart-button">
	       <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
	   </button>
	   <?php echo $block->getChildHtml('', true) ?>
       </div>	
   </div>	
</div>	
<?php endif; ?>	
<script type="text/x-magento-init">	
   {	
       "#product_addtocart_form": {	
	   "Magento_Catalog/product/view/validation": {
	       "radioCheckboxClosest": ".nested"
	   }
       }	
   }	
</script>	
<?php if (!$block->isRedirectToCartEnabled()) : ?>	
<script type="text/x-magento-init">	
   {	
       "#product_addtocart_form": {	
	   "catalogAddToCart": {
	       "bindSubmit": false
	   }
       }	
   }	
</script>	
<?php endif; ?>